const BADREQUEST = 400;
const UNATHORIZED = 401;
const FORBIDDEN = 403;
const NOTFOUND = 404;
const SERVERERROR = 500;

module.exports = {
  BADREQUEST, NOTFOUND, SERVERERROR, UNATHORIZED, FORBIDDEN,
};
